/** Regenerate the explicit server import map after adding a locale or namespace. */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { format, resolveConfig } from 'prettier';
import { fileURLToPath } from 'node:url';
const style = await resolveConfig(fileURLToPath(import.meta.url));
const formatted = (source: string) => format(source, { ...style, parser: 'typescript' });
import { locales } from '../apps/web/src/i18n/registry';
const root = new URL('../apps/web/messages/', import.meta.url);
const dirs = [...locales].sort();
const namespaces = (await readdir(new URL('en/', root)))
  .filter((x) => x.endsWith('.json'))
  .map((x) => x.slice(0, -5))
  .sort();
let body = '// Generated by pnpm exec tsx scripts/i18n-manifest.ts. Server imports only.\n';
body += "import 'server-only';\n";
body += `export const namespaces = ${JSON.stringify(namespaces)} as const;\nexport type Namespace = (typeof namespaces)[number];\n`;
body += 'export const messageImports = {\n';
const hash = createHash('sha256');
for (const locale of dirs) {
  body += `${JSON.stringify(locale)}: {\n`;
  for (const ns of namespaces) {
    hash.update(await readFile(new URL(`${locale}/${ns}.json`, root)));
    body += `${JSON.stringify(ns)}: () => import('../../messages/${locale}/${ns}.json').then(m => m.default),\n`;
  }
  body += '},\n';
}
body += '} as const;\n';
await writeFile(new URL('../apps/web/src/i18n/imports.ts', import.meta.url), await formatted(body));
await writeFile(
  new URL('../apps/web/src/i18n/version.ts', import.meta.url),
  `// Content version separates dictionary caches across deployments.\nexport const messageVersion = '${hash.digest('hex').slice(0, 16)}';\n`,
);
// A compact, type-only contract for tooling and new typed call sites; no dictionary is bundled.
function flatten(value: any, prefix = ''): Record<string, string> {
  if (typeof value === 'string') return { [prefix]: value };
  return Object.assign(
    {},
    ...Object.entries(value).map(([k, v]) => flatten(v, prefix ? `${prefix}.${k}` : k)),
  );
}
let types = '// Generated from English source messages.\nexport interface MessageParameters {\n';
for (const namespace of namespaces) {
  const source = flatten(JSON.parse(await readFile(new URL(`en/${namespace}.json`, root), 'utf8')));
  types += `${JSON.stringify(namespace)}: {\n`;
  for (const [key, value] of Object.entries(source)) {
    const args = [...new Set([...value.matchAll(/\{([\w]+)(?:\}|,)/g)].map((match) => match[1]))];
    types += `${JSON.stringify(key)}: {${args.map((name) => `${JSON.stringify(name)}: ${new RegExp('\\{' + name + ',\\s*(plural|selectordinal|number)\\b').test(value) ? 'number' : 'string | number'}`).join(';')}};\n`;
  }
  types += '};\n';
}
types +=
  '}\nexport type MessageKey<N extends keyof MessageParameters> = keyof MessageParameters[N];\n';
await writeFile(
  new URL('../apps/web/src/i18n/message-types.d.ts', import.meta.url),
  await formatted(types),
);
